services:
  mysql:
    image: "mysql:8.0"
    environment:
      - "MYSQL_ROOT_PASSWORD=root_password"
      - "MYSQL_DATABASE=demo"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
